# Generated by Django 4.1.7 on 2023-03-01 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteModeules', '0002_calcmodules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icons',
            old_name='details',
            new_name='definition',
        ),
        migrations.AddField(
            model_name='icons',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='CalcModules',
        ),
    ]
