# Generated by Django 4.1.7 on 2023-03-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteModeules', '0005_calculator_module_post_delete_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='text_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='text_id',
        ),
    ]
